-- Implement Database
CREATE DATABASE CarRental;

USE CarRental;

CREATE TABLE Customer (
  CustomerID INT IDENTITY(10000001,1) NOT NULL PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  City VARCHAR(50) NOT NULL,
  State VARCHAR(50) NOT NULL,
  ZIP VARCHAR(20) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Age INT NOT NULL,
  DrivingLicenseNumber VARCHAR(50) NOT NULL
);

CREATE TABLE CustomerFeedback (
  FeedbackID INT IDENTITY(20000001,1) NOT NULL PRIMARY KEY,
  CustomerID INT NOT NULL,
  Feedback VARCHAR(500) NOT NULL,
  DatePosted DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE Discount (
  DiscountID INT IDENTITY(30000001,1) NOT NULL PRIMARY KEY,
  DiscountAmount DECIMAL(10,2) NOT NULL,
  DiscountType VARCHAR(50) NOT NULL
);

CREATE TABLE Customer_Discount (
  CustomerDiscountID INT IDENTITY(40000001,1) NOT NULL PRIMARY KEY,
  CustomerID INT NOT NULL,
  DiscountID INT NOT NULL,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
  FOREIGN KEY (DiscountID) REFERENCES Discount(DiscountID)
);



CREATE TABLE Vehicle (
  VehicleID INT IDENTITY(50000001,1) NOT NULL PRIMARY KEY,
  Color VARCHAR(50) NOT NULL,
  Manufacturer VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  Type VARCHAR(50) NOT NULL,
  Mileage INT NOT NULL,
  Status VARCHAR(50) NOT NULL
);

CREATE TABLE Insurance (
  InsuranceID INT IDENTITY(60000001,1) NOT NULL PRIMARY KEY,
  InsuranceType VARCHAR(50) NOT NULL,
  VehicleID INT NOT NULL,
  Provider VARCHAR(100) NOT NULL,
  PolicyNumber VARCHAR(50) NOT NULL,
  ExpirationDate DATETIME NOT NULL,
  FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID)
);

CREATE TABLE Location (
  LocationID INT IDENTITY(70000001,1) NOT NULL PRIMARY KEY,
  Address VARCHAR(100) NOT NULL,
  City VARCHAR(50) NOT NULL,
  State VARCHAR(50) NOT NULL,
  ZIP VARCHAR(20) NOT NULL
);

CREATE TABLE VehicleMaintenance (
  MaintenanceID INT IDENTITY(80000001,1) NOT NULL PRIMARY KEY,
  MaintenanceDate DATETIME NOT NULL,
  MaintenanceRate DECIMAL(10,2) NOT NULL,
  VehicleID INT NOT NULL,
  FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID)
);

CREATE TABLE Branch (
  BranchID INT IDENTITY(90000001,1) NOT NULL PRIMARY KEY,
  Email VARCHAR(50),
  Address VARCHAR(100) NOT NULL,
  City VARCHAR(50) NOT NULL,
  State VARCHAR(50) NOT NULL,
  Zip VARCHAR(10) NOT NULL,
  Phone VARCHAR(20)
);

CREATE TABLE Employee (
   EmployeeID INT IDENTITY(100000001,1) NOT NULL PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Position VARCHAR(50) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  City VARCHAR(50) NOT NULL,
  State VARCHAR(50) NOT NULL,
  Zip VARCHAR(10) NOT NULL,
  Phone VARCHAR(20),
  Email VARCHAR(50),
  BranchID INT NOT NULL,
  CONSTRAINT FK_Employee_Branch FOREIGN KEY (BranchID) REFERENCES Branch(BranchID)
);

CREATE TABLE Rental (
  RentalID INT IDENTITY(110000001,1) NOT NULL PRIMARY KEY,
  CustomerID INT NOT NULL,
  VehicleID INT NOT NULL,
  RentalStartDate DATETIME NOT NULL,
  RentalEndDate DATETIME NOT NULL,
  RentalRate DECIMAL(10,2) NOT NULL,
  InsuranceID INT NOT NULL,
  DiscountID INT NOT NULL,
  FeedbackID INT NULL,
  BranchID INT NOT NULL,
  PickupLocation INT NOT NULL,
  DropoffLocation INT NULL,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
  FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID),
  FOREIGN KEY (InsuranceID) REFERENCES Insurance(InsuranceID),
  FOREIGN KEY (DiscountID) REFERENCES Discount(DiscountID),
  FOREIGN KEY (FeedbackID) REFERENCES CustomerFeedback(FeedbackID),
  FOREIGN KEY (BranchID) REFERENCES Branch(BranchID),
  FOREIGN KEY (PickupLocation) REFERENCES Location(LocationID),
  FOREIGN KEY (DropoffLocation) REFERENCES Location(LocationID)
);

CREATE TABLE Rental_Employee (
  RentalEmployeeID INT IDENTITY(120000001,1) NOT NULL PRIMARY KEY,
  RentalID INT NOT NULL,
  EmployeeID INT NOT NULL,
  CONSTRAINT FK_Rental_Employee_Rental FOREIGN KEY (RentalID) REFERENCES Rental(RentalID),
  CONSTRAINT FK_Rental_Employee_Employee FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
);

CREATE TABLE Bill (
  BillID INT IDENTITY(130000001,1) NOT NULL PRIMARY KEY,
  RentalID INT NOT NULL,
  TotalAmount DECIMAL(10,2) NOT NULL,
  DateIssued DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Bill_Rental FOREIGN KEY (RentalID) REFERENCES Rental(RentalID)
);

CREATE TABLE Payment (
  PaymentID INT IDENTITY(140000001,1) NOT NULL PRIMARY KEY,
  BillID INT NOT NULL,
  PaymentAmount DECIMAL(10,2) NOT NULL,
  PaymentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  PaymentMethod VARCHAR(50) NOT NULL,
  CONSTRAINT FK_Payment_Bill FOREIGN KEY (BillID) REFERENCES Bill(BillID)
);
